### ISSUE TITLE
Copyright Issues

### ISSUE THREAD

**Issue by utam0k** [oliverdding/oliverdding#1]
Can I ask you to stop using my profile image?

**Comment by oliverdding** [comment]
@utam0k I'm sorry to bother you, I found this picture in twitter and didn't know it's yours. I would change it right now.😣

**Comment by oliverdding** [comment]
@utam0k May I ask for a day for checking other accounts that using this avatar? My computer is not nearby right now, and I promise everything would be down tomorrow.

**Comment by utam0k** [comment]
Thanks for taking care of that!
